### PR TITLE
Suggestion of design for multiple days

### PR DESCRIPTION
**Pull request by Jamnoran**

### CODE REVIEW

**Comment by darrrrUC** [comment]
Får warn, kanske lika bra att få bort den innan merge.

[Vue warn]: Extraneous non-props attributes (city) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. 
  at <WeatherCard city="uppsala (Lat: 59.8586126, Lon: 17.6387436)" weatherDay= {date: '2024-07-02', temperature: 20.3}date: "2024-07-02"temperature: 20.3[[Prototype]]: Object isLoading=false > 
  at <VCol> 
  at <VRow key=0 class="mb-4" > 
  at <VContainer fluid="" > 
  at <WeatherDisplay city="uppsala (Lat: 59.8586126, Lon: 17.6387436)" weather= (11) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] isLoading=false >

**Comment by Jamnoran** [comment]
> Får warn, kanske lika bra att få bort den innan merge.
> 
> [Vue warn]: Extraneous non-props attributes (city) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. at <WeatherCard city="uppsala (Lat: 59.8586126, Lon: 17.6387436)" weatherDay= {date: '2024-07-02', temperature: 20.3}date: "2024-07-02"temperature: 20.3[[Prototype]]: Object isLoading=false > at at at at <WeatherDisplay city="uppsala (Lat: 59.8586126, Lon: 17.6387436)" weather= (11) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] isLoading=false >

Absolut! 
Jag stapplar mig fram fortfarande på trevande ben :D

**Comment by Jamnoran** [comment]
Mergat in senaste from main nu också

**Comment by darrrrUC** [comment]
> > Får warn, kanske lika bra att få bort den innan merge.
> > [Vue warn]: Extraneous non-props attributes (city) were passed to component but could not be automatically inherited because component renders fragment or text root nodes. at <WeatherCard city="uppsala (Lat: 59.8586126, Lon: 17.6387436)" weatherDay= {date: '2024-07-02', temperature: 20.3}date: "2024-07-02"temperature: 20.3[[Prototype]]: Object isLoading=false > at at at at <WeatherDisplay city="uppsala (Lat: 59.8586126, Lon: 17.6387436)" weather= (11) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}] isLoading=false >
> 
> Absolut! Jag stapplar mig fram fortfarande på trevande ben :D

haha ingen fara, javascript random error lite här å var :D blev riktigt nice jue!

**Pull request merged**
